### ISSUE TITLE
TOKEN del server

### ISSUE THREAD

**Issue by rubenchos6** [ITAM4Code/discord-bot#2]
Segun yo, para conectar al bot se necesita el token del servidor, y para eso necesitamos a un poderosisimo admin

**Comment by rubenchos6** [comment]
https://discord.com/developers/applications

**Comment by raarv** [comment]
Deberíamos tener un servidor para hacer pruebas y no llegar a afectar a los demás, cuando tengamos algo funcional pedimos se incorpore.

**Comment by rubenchos6** [comment]
La otra sería dirigir todos los mensajes al canal que ya tenemos del grupo o armar otro canal, porque si sacamos el ID del canal, podemos redirigir todos los mensajes a ese canal, para que se vea que estamos haciendo progresos.

**Comment by raarv** [comment]
Pero nos estamos limitando a hacer pruebas en un canal de texto específico, y cada que queramos un nuevo canal tenemos que pedírselo a un administrador, además ese administrador tendría que pasarnos los tokens y modificar los permisos de notificaciones para que las demás personas no se vean inundadas de spam. Si luego queremos hacer pruebas en canales de voz de nuevo pasa lo mismo. 

Esto es para no estar quitándole tiempo a los de la mesa y que tengamos total libertad de probar lo que queramos.

Respecto a lo del progreso, se puede tener el bot con las funciones terminadas en el discord con los demás para que lo puedan ver y usar. Esto solo es para hacer pruebas.

**Comment by rubenchos6** [comment]
Me convenciste

**Comment by rubenchos6** [comment]
Se compartió el archivo .env en discord. Aios
