### ISSUE TITLE
Asignación de roles al reaccionar en emoji

### ISSUE THREAD

**Issue by raarv** [ITAM4Code/discord-bot#5]
Me gustaría que una de las principales funciones sea el poder asignar un rol cuando un usuario reaccione con un emoji en particular a una publicación.  Podríamos basarnos en este [código](https://github.com/stroupbslayen/Other-Discord-Bots-async/blob/master/Emoji%20Roles/emoji_roles.py)

Pienso que debería haber un rol por proyecto, para que podamos manejar mejor las notificaciones y hacer menciones de todos los que estén trabajando en cierto proyecto, el problema que podría presentarse es que es mucho trabajo andar viendo quién pertenece a cada proyecto y tener que acudir a los miembros de @mesa para poder asignar el rol, por lo tanto podemos tener un canal de texto donde se ponga una lista con los proyectos y un emoji asociado a cada uno de manera que al darle click, el bot asigne ese rol.

**Comment by rubenchos6** [comment]
Me gusta la idea de asignar roles por proyecto, no se si me gusta asignarlo con un emoji particular. Si no se me ocurre alguna otra forma, estaré de acuerdo jajaja

**Comment by rubenchos6** [comment]
Ya chequé el código y se ve bastante bien. Pero confirmo que la idea de hacer un comando estaría más fácil que los emojis jajaja

**Comment by raarv** [comment]
suena bien, hagamos eso

**Comment by ossanche** [comment]
True! 
:heart:
